POST http://localhost:3000/api/auth/register
content-Type: application/json

{
    "username": "minh",
    "password": "12345"
}

##############

POST http://localhost:3000/api/auth/login
content-Type: application/json

{
    "username": "minh",
    "password": "12345" 
}

##############
POST http://localhost:3000/api/posts
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY0MTE0Mjg3NjEyNTg4NTEzNTc1Y2MiLCJpYXQiOjE2NTA3MjUxODZ9.p-3qYZ0MhREjxcTi3nhAgD_26ZpCmY0G1b6co3hROFs

{
    "title": "reactJs",
    "description": "framework",
    "url": "reactjs.org",
    "status": "LEARNING" 
}

##############
GET http://localhost:3000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY0MTE0Mjg3NjEyNTg4NTEzNTc1Y2MiLCJpYXQiOjE2NTA3MjUxODZ9.p-3qYZ0MhREjxcTi3nhAgD_26ZpCmY0G1b6co3hROFs

##############
PUT http://localhost:3000/api/posts/62674e43756db131c057f715
content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY0MTE0Mjg3NjEyNTg4NTEzNTc1Y2MiLCJpYXQiOjE2NTA3MjUxODZ9.p-3qYZ0MhREjxcTi3nhAgD_26ZpCmY0G1b6co3hROFs

{
    "title": "reactJS update",
    "description": "framework2",
    "url": "reactjs.org",
    "status": "LEARNING"
}

##############
DELETE  http://localhost:3000/api/posts/62674e43756db131c057f715
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY0MTE0Mjg3NjEyNTg4NTEzNTc1Y2MiLCJpYXQiOjE2NTA3MjUxODZ9.p-3qYZ0MhREjxcTi3nhAgD_26ZpCmY0G1b6co3hROFs

 